### ISSUE TITLE
Feature Request: device attribute

### ISSUE THREAD

**Issue by jshvrsn** [mattlqx/cookbook-efs#7]
Could you add an attribute to override the device for people who aren't using AWS DNS? We use our own private DNS and would like to use your excellent cookbook to mount an EFS drive, but we need to be able to pass an IP instead of using the default AWS DNS entry.

For example:
```
10.0.0.1:/
```
instead of 
```
fs-12345678.efs.us-east-1.amazonaws.com:/
```

**Comment by mattlqx** [comment]
This is reasonable, it would take a small amount of refactoring. Not sure why you wouldn't just use a `mount` resource at that point though?

**Comment by jshvrsn** [comment]
Good point. I can try that first and see if it works for us. Thanks!
