### ISSUE TITLE
Hello Matt

### ISSUE THREAD

**Issue by ghost** [mattlqx/cookbook-efs#8]

**Comment by ghost** [comment]
Hello Matt,

Thank you so much for the recipes!
I am newbie to chef and using your recipes in our test env to setup EFS but I am running into the following issue 

undefined method `mount_efs' for cookbook: efs, recipe: default :Chef::Recipe
ERROR: undefined method `mount_efs' for cookbook: efs, recipe: default :Chef::Recipe
FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by mattlqx** [comment]
You would have to post your code but it appears that you're not using the Chef DSL correctly to define the resource. Sorry for the delay here, I'd imagine one way or another, you're past this now.
